# Generated by Django 2.1.5 on 2019-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('uri', models.TextField(verbose_name='URI')),
                ('code', models.PositiveIntegerField(verbose_name='Код ответа')),
                ('size', models.PositiveIntegerField(verbose_name='Размер в байтах')),
            ],
        ),
    ]
