# Generated by Django 2.1.5 on 2019-06-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-created_at',), 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
