# Generated by Django 2.1.5 on 2019-06-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20190609_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
