# Generated by Django 2.1.5 on 2019-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_auto_20190610_1435'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['ip_address', 'method', 'uri', 'code'], name='complex_search_idx'),
        ),
    ]
