# Generated by Django 2.1.5 on 2019-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_auto_20190610_1436'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-created_at'], name='created_at_idx'),
        ),
    ]
