# Generated by Django 2.1.5 on 2019-06-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_auto_20190610_1453'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='complex_search_idx',
        ),
    ]
