# Generated by Django 2.1.5 on 2019-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_auto_20190610_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ip_address',
            field=models.CharField(max_length=255, verbose_name='IP адрес'),
        ),
    ]
